### ISSUE TITLE
dependency yubico-python has been changed to yubico-client

### ISSUE THREAD

**Issue by bzdk** [Kami/django-yubico-authentication-backend#4]
Error info:
Error importing authentication backend django_yubico.backends.YubicoBackend: "No module named yubico.yubico"

See:
https://github.com/Kami/python-yubico-client

**Comment by Kami** [comment]
Good catch.

Looks like I've failed to update all the references to the yubico library when I migrated to yubico_client.

I'll push a fix shortly.

**Comment by Kami** [comment]
I've published 0.3.1 which should fix this issue to PyPi - https://pypi.python.org/pypi/django_yubico/0.3.1

**Comment by bzdk** [comment]
@Kami Thank you very much for the fix. I have verified it works.

**Comment by Kami** [comment]
No problem and glad that it works.
